-- MySQL Script generated by MySQL Workbench
-- Sat Apr 19 09:57:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Multimedia` DEFAULT CHARACTER SET utf8 ;
USE `Multimedia` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Multimedia`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NULL,
  `password` VARCHAR(64) NULL,
  `email` VARCHAR(64) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Multimedia`.`Skin` (
  `skin_id` INT NOT NULL AUTO_INCREMENT,
  `skin_name` VARCHAR(64) NULL,
  PRIMARY KEY (`skin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Favorite_Skin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Multimedia`.`User_Favorite_Skin` (
  `user_id` INT NOT NULL,
  `skin_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `skin_id`),
  INDEX `fk_User_has_Favorite_Skin_Favorite_Skin1_idx` (`skin_id` ASC) VISIBLE,
  INDEX `fk_User_has_Favorite_Skin_User_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Favorite_Skin_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Favorite_Skin_Favorite_Skin1`
    FOREIGN KEY (`skin_id`)
    REFERENCES `mydb`.`Skin` (`skin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
